name = "tactical-index-api"
main = "src/index.ts"
compatibility_date = "2024-01-26"

[[d1_databases]]
binding = "DB"
database_name = "tactical-curriculum-db"
database_id = "25f74a5f-6030-41a9-ae14-061a2e594e13"
